apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app
spec:
  replicas: 1
  selector:
    matchExpressions:
      - { key: app, operator: IN, values: [second-app, first-app] }
    # matchLabels:
    #   app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: kub-second-app
          image: javalord001/kub-first-app:v3
